CREATE SCHEMA LAB10;
CREATE DATABASE IF NOT EXISTS `LAB10`
CREATE TABLE IF NOT EXISTS `LAB10`.`datos_serial`
(
	`Id` INT AUTO_INCREMENT PRIMARY KEY,
    `Mensaje_Serial` TEXT,
    `Tiempo` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
SELECT * FROM `LAB10`.`datos_serial`
TRUNCATE TABLE `LAB10`.`datos_serial`
SELECT COUNT(*) FROM datos_serial

